### ISSUE TITLE
Roman - For your amusement...

### ISSUE THREAD

**Issue by VastSky** [Schm1tz1/ESPressIoT#16]
Hello Roman - this might interest you!

Github project repository: [**bleeding-edge-Ranciliopid**
](https://github.com/medlor/bleeding-edge-ranciliopid/releases/tag/2.6.0)

Project website: **[http://rancilio-pid.de/](http://rancilio-pid.de/)**

Ed

**Comment by Schm1tz1** [comment]
Hi Ed,
thanks a lot for sharing - looks very familiar ;-). Probably this any my project have so much in common that this would have been a good candidate for a more "abstract" approach. 
Always a good thing if one can work together in these Espresso PID projects - joint effort instead of reinventing the wheel. Unfortunately many projects pop up in parallel, there is hardly any communication and a lot of copy&paste instead of collaboration using forks, branches and pull request. 
Anyways - nice project but I'm too busy at the moment to join it or work on combining the two projects. 

Have a nice day!
Roman
